export PATH=/usr/local/opt/python/libexec/bin:/Applications/MacVim.app/Contents/bin:$PATH

export EDITOR=vim

source /usr/local/etc/bash_completion.d/*

alias ls="ls -G"
alias git=hub
alias vscode="open -a \"Visual Studio Code\""

export HISTFILESIZE=5000
export HISTSIZE=$HISTFILESIZE

if [ -f "/usr/local/opt/bash-git-prompt/share/gitprompt.sh" ]; then
__GIT_PROMPT_DIR="/usr/local/opt/bash-git-prompt/share"
source "/usr/local/opt/bash-git-prompt/share/gitprompt.sh"
fi

GIT_PROMPT_THEME=Solarized
GIT_PROMPT_SHOW_UPSTREAM=1

~/Code/dotfiles/bin/docker-prune