export PATH=./node_modules/.bin/:~/.bin:~/Library/Python/2.7/bin/:/usr/local/sbin:/usr/local/bin:$PATH

export EDITOR=vim

for d in ~/.local/*
do
    export PATH=$d/bin:$PATH
done

source /usr/local/bin/virtualenvwrapper.sh

source /usr/local/etc/bash_completion.d/*

export iraf="$HOME/.local/iraf/"

# Add iraf setup commands
if [ -e /Users/adam/.iraf/setup.sh ]; then
    source /Users/adam/.iraf/setup.sh
fi
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

source ~/.dotfiles/config/git-completion.bash

alias ls="ls -G"
alias git=hub

export GOPATH=$HOME/Documents/Code/go
export PATH=$PATH:$GOPATH/bin

export HISTFILESIZE=5000
export HISTSIZE=$HISTFILESIZE

export NVM_DIR="/Users/adam/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
    source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
fi
GIT_PROMPT_THEME=Solarized
GIT_PROMPT_SHOW_UPSTREAM=1

docker-prune
